### ISSUE TITLE
The name of the command is checked with the import name, not the command name

### ISSUE THREAD

**Issue by larto42** [typeofweb/typeofweb-discord-bot#36]
Shouldn't command from the message be compared to the field `name` in the command's class instead of the key in `allCommands` object? (in index.ts)

Now the name is used only as the presentational value. The check of the command uses whatever name you use as the import of that command to the index.ts file. 

As an addition it creates a problem if I wanted to make a command with name containing not only letters, but digits as well. I can't just update the regex to account for it. If the command name starts with the digit it's not the valid variable name, thus can't be used as import name value and rules out this name as a possibility altogether.

**Comment by mmiszy** [comment]
Good catch @larto42!

**Comment by mmiszy** [comment]
Fixed in 5c065228cbb1cd1d40173c4f234996df02e926ef
